name: cooking_daddy
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/officialLogo.png
  
  fonts:
    - family: PixelifySans
      fonts:
        - asset: fonts/static/PixelifySans-Regular.ttf
        - asset: fonts/static/PixelifySans-Medium.ttf
          weight: 500
        - asset: fonts/static/PixelifySans-SemiBold.ttf
          weight: 600
        - asset: fonts/static/PixelifySans-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/officialLogo.png"